version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8088:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example

      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db1
      MYSQL_ROOT_PASSWORD: pass  # Set root password here
    ports:
      - "3307:3306"  # External port can be configured

#  redis:
#    image: redis:latest
#    restart: always
#    ports:
#        - "6379:6379"