// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"encoding/json"
)

type User struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Uuid      string
	Roles     json.RawMessage
	Password  string
	Email     string
	Username  sql.NullString
}
